### ISSUE TITLE
Breaks down UTF when use cyrilic

### ISSUE THREAD

**Issue by tychodaimon** [misd-service-development/php-linkify#24]
For example: Линк: https://ru.wikipedia.org/wiki/Футбол
to fix just add '**u**' after ~ in Your patterns
@thewilkybarkid

**Comment by tychodaimon** [comment]
just change:
 $pattern = '~(?xi)
                \b
                (?<!=)           # Not part of a query string
                [A-Z0-9._\'%+-]+ # Username
                @                # At
                [A-Z0-9.-]+      # Domain
                \.               # Dot
                [A-Z]{2,4}       # Something
        ~';
with:
 $pattern = '~(?xi)
                \b
                (?<!=)           # Not part of a query string
                [A-Z0-9._\'%+-]+ # Username
                @                # At
                [A-Z0-9.-]+      # Domain
                \.               # Dot
                [A-Z]{2,4}       # Something
        ~u';

**Comment by tychodaimon** [comment]
![fixutf](https://user-images.githubusercontent.com/3998058/29181898-86a1efbc-7e05-11e7-9be0-c34c6021ef60.png)

**Comment by tychodaimon** [comment]
https://github.com/misd-service-development/php-linkify/pull/23 please merge this into master @edea @arthurdarcet @JeebsUK @bartgloudemans @jarofgreen

**Comment by thewilkybarkid** [comment]
[v1.1.4](https://github.com/misd-service-development/php-linkify/releases/tag/v1.1.4) released.
